USE esgroadmap;

CREATE TABLE company_universe (
    `Company` VARCHAR(255) Primary Key,
    `x` VARCHAR(255),
    `Member of the S&P500` VARCHAR(255),
    `Member of the Russell 1000 Index` VARCHAR(255),
    `source` VARCHAR(255),
    `Scraping code set up ?` VARCHAR(255),
    `Ticker(s)` VARCHAR(255),
    `PR Agency` VARCHAR(255),
    `Example 2020 company PR agency press release URL` TEXT,
    `Domain` VARCHAR(500),
    `Company global/main press - news release site URL` TEXT,
    `Subscribed to press releases esgroadmap@gmail.com ?` VARCHAR(255),
    `Subscribed to press releases jameskijani@gmail.com ?` VARCHAR(255),
    `Plain text press release subscription possible? (yes/no)` VARCHAR(3),
    `Company annual reports page URL` TEXT,
    `Company annual report 2020 URL of pdf document (including 10-k)` TEXT,
    `Company sustainability / ESG reports page URL` TEXT,
    `Company Sustainability / ESG report 2020 URL of pdf document` TEXT,
    `Country` VARCHAR(255),
    `NAICS #1` VARCHAR(10),
    `2017 NAICS TITLE` VARCHAR(255),
    `NAICS #2` VARCHAR(10),
    `2017 NAICS TITLE.1` VARCHAR(255),
    `NAICS #3` VARCHAR(10),
    `2017 NAICS TITLE.2` VARCHAR(255),
    `NAICS #4` VARCHAR(10),
    `2017 NAICS TITLE.3` VARCHAR(255),
    `NAICS #5` VARCHAR(10),
    `2017 NAICS TITLE.4` VARCHAR(255),
    `WORKED BY:` VARCHAR(255),
    `COMMENTS / NOTES` TEXT,
    `Carbon sentence available ?` VARCHAR(255)
);
